using Timberborn.AttractionsUI;
using Timberborn.AutomationUI;
using Timberborn.BatchControl;
using Timberborn.BuildingsUI;
using Timberborn.ConstructionSitesUI;
using Timberborn.CoreUI;
using Timberborn.EntitySystem;
using Timberborn.HaulingUI;
using Timberborn.StatusSystemUI;

namespace Timberborn.AttractionsBatchControl;

internal class AttractionsBatchControlRowFactory
{
	private readonly VisualElementLoader _visualElementLoader;

	private readonly BuildingBatchControlRowItemFactory _buildingBatchControlRowItemFactory;

	private readonly StatusBatchControlRowItemFactory _statusBatchControlRowItemFactory;

	private readonly ConstructionSitePriorityBatchControlRowItemFactory _constructionSitePriorityBatchControlRowItemFactory;

	private readonly AttractionBatchControlRowItemFactory _attractionBatchControlRowItemFactory;

	private readonly AttractionLoadRateBatchControlRowItemFactory _attractionLoadRateBatchControlRowItemFactory;

	private readonly GoodConsumingAttractionBatchControlRowItemFactory _goodConsumingAttractionBatchControlRowItemFactory;

	private readonly HaulCandidateBatchControlRowItemFactory _haulCandidateBatchControlRowItemFactory;

	private readonly AutomatableBatchControlRowItemFactory _automatableBatchControlRowItemFactory;

	public AttractionsBatchControlRowFactory(VisualElementLoader visualElementLoader, BuildingBatchControlRowItemFactory buildingBatchControlRowItemFactory, StatusBatchControlRowItemFactory statusBatchControlRowItemFactory, ConstructionSitePriorityBatchControlRowItemFactory constructionSitePriorityBatchControlRowItemFactory, AttractionBatchControlRowItemFactory attractionBatchControlRowItemFactory, AttractionLoadRateBatchControlRowItemFactory attractionLoadRateBatchControlRowItemFactory, GoodConsumingAttractionBatchControlRowItemFactory goodConsumingAttractionBatchControlRowItemFactory, HaulCandidateBatchControlRowItemFactory haulCandidateBatchControlRowItemFactory, AutomatableBatchControlRowItemFactory automatableBatchControlRowItemFactory)
	{
		_visualElementLoader = visualElementLoader;
		_buildingBatchControlRowItemFactory = buildingBatchControlRowItemFactory;
		_statusBatchControlRowItemFactory = statusBatchControlRowItemFactory;
		_constructionSitePriorityBatchControlRowItemFactory = constructionSitePriorityBatchControlRowItemFactory;
		_attractionBatchControlRowItemFactory = attractionBatchControlRowItemFactory;
		_attractionLoadRateBatchControlRowItemFactory = attractionLoadRateBatchControlRowItemFactory;
		_goodConsumingAttractionBatchControlRowItemFactory = goodConsumingAttractionBatchControlRowItemFactory;
		_haulCandidateBatchControlRowItemFactory = haulCandidateBatchControlRowItemFactory;
		_automatableBatchControlRowItemFactory = automatableBatchControlRowItemFactory;
	}

	public BatchControlRow Create(EntityComponent entity)
	{
		return new BatchControlRow(_visualElementLoader.LoadVisualElement("Game/BatchControl/BatchControlRow"), entity, _buildingBatchControlRowItemFactory.Create(entity), _attractionBatchControlRowItemFactory.Create(entity), _attractionLoadRateBatchControlRowItemFactory.Create(entity), _haulCandidateBatchControlRowItemFactory.Create(entity), _constructionSitePriorityBatchControlRowItemFactory.Create(entity), _goodConsumingAttractionBatchControlRowItemFactory.Create(entity), _automatableBatchControlRowItemFactory.Create(entity), _statusBatchControlRowItemFactory.Create(entity));
	}
}
